#!/bin/bash
#automate your nightly tasks quicker


#run scripts

#check folder (refresh script list)

for entry in "$PWD/night"/*
do
    if [[ "$entry" == *".sh"* ]]
        then
            echo "NIGHTLY: running $entry"
            env -i $entry
    fi
done
